# Generated by Django 2.0.1 on 2019-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='github_account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='work_history',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='indeed_account',
            field=models.CharField(max_length=100),
        ),
    ]
