# Generated by Django 2.0.1 on 2019-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190906_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_second_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
