# Generated by Django 2.0.1 on 2019-09-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190906_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Status'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Status'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Status'),
        ),
    ]
