# Generated by Django 2.0.1 on 2019-09-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190906_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Phase')),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status'},
        ),
    ]
