# Generated by Django 2.0.1 on 2019-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190906_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='advertising_phrase',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.CharField(default='', max_length=750),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='work_history',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
