# Generated by Django 2.0.1 on 2019-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20190909_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='indeed_account',
        ),
        migrations.AddField(
            model_name='instructor',
            name='github_account_link',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin_account_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
