# Generated by Django 2.0.1 on 2019-10-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20190918_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='Foto instructor'),
        ),
    ]
