# Generated by Django 2.0.1 on 2019-10-11 16:02

import autoslug.fields
from django.db import migrations
from landing.models import Course

def migrate_data_forward(apps, schema_editor):
    for instance in Course.objects.all():
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20191011_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True,max_length=200),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
